#!/usr/bin/env bash

sudo apt update
sudo apt install -y llvm lld llvm-dev liblld-dev clang libclang-dev libglib2.0-dev libgtk-4-dev libadwaita-1-dev git

wget https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz -O /tmp/zig.tar.xz
tar -xf /tmp/zig.tar.xz -C $HOME/.local

mv $HOME/.local/zig-linux-x86_64-0.14.0.tar.xz $HOME/.local/zig
export PATH="$HOME/.local/zig:$PATH"

git clone https://github.com/ghostty-org/ghostty $HOME/personal/ghostty

(
    cd $HOME/personal/ghostty
    zig build -p $HOME/.local -Doptimize=ReleaseFast
)
