#!/usr/bin/env bash

sh -c "$(curl -sS https://starship.rs/install.sh)" -- --yes
sudo apt install -y zsh
hash -r
sudo chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
